### ISSUE TITLE
Cast / Cast and Role Issue

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamoriplugin#100]
not working properly

**Comment by da3dsoul** [comment]
Yep. Not sure why, I left some comments.

**Comment by bigretromike** [comment]
I did fix this. Now i'm tweaking it ;-)

**Comment by da3dsoul** [comment]
How do view the cast for testing? It doesn't show in the info section, unless there is a different info section I'm not familiar with.

**Comment by bigretromike** [comment]
Cast works on 'continue watching' and on series info (Episode View) not on series name itself.
And it works with 'i' or with Menu Info you added.

**Comment by bigretromike** [comment]
Also it require to use  the build that isin't merge into official JMMServer but is in my repo
