### ISSUE TITLE
Sorting define by User 

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamoriplugin#14]
by @bmfrosty

```
Yes. I think I'm explaining poorly, and didn't fully understand the 
problem when I opened the issue. What I'm talking about is that 
most series have multiple names. The sorting is something to be handled separately. 

5 Centimeters per Second is a great example. In AniDB, let me give you 3 examples:

 Main Title (x-jat) is: 
Byousoku 5 Centimeter 

Official Title in Japanese is:
 秒速5センチメートル 

Official Title in English is: 
5 Centimeters per Second 

The Main title is normally a romanji representation of the Official Japanese 
title, I think. 

I reads to me like the XML (I haven't checked out 1.0.5 yet) is sorted by 
the Official en title, but displays the Main title. Theoretically, Kodi should 
sort the series alphabetically, but we should have the ability to chose 
which for of title to prefer. Since there's always a main title, it makes sense to 
use that, but what I'm looking for is for it to be able to pick the official english
 title if there is one, but if not, then use the main title instead.
```

**Comment by bigretromike** [comment]
Currently we need to add ANY sort method to be able to pick from menu

**Comment by bmfrosty** [comment]
Agreed.  We also need to be able to choose a naming preference.  Just using "Main Title" from anidb is not enough.

**Comment by bigretromike** [comment]
Thats are you prefs then? Main Title and Original Name from AniDB would be ok? or is there more ?

**Comment by bmfrosty** [comment]
It has to have a fallback to Main Title in case the preferred title doesn't
exist in the language of the users choosing.  For my case, I'd pick
english, so I'd get:

Official Title (en)

then

Main Title

but Main Title would only kick in if Official Title (en) doesn't exist.

I guess for most it would come down to a language preference that would
pick the Official Title in the language of the user's preference, and if
that doesn't exist, it would fall back to the Main Title, since the Main
Title always exists.  Currently the behaviour is to just use the main
title.  Which is why "秒速5センチメートル" in AniDB displays as "Byousoku 5
Centimeter" instead of "5 Centimeters per Second" -
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=4568

Thanks,

-Ben

**Comment by bigretromike** [comment]
I think you have right. Official Title (en) then Main Title. 
I see that JMM didn't index all of my collection because I know I own that move.
I will finish the work with function that build menus when you browser collection, and then I will get into Sorting :+1:

**Comment by bigretromike** [comment]
This is the JMMServer thing to fix. Currently it servers titles like this:
```  title="Byousoku 5 Centimeter"   original_title="Byousoku 5 Centimeter|5 cm per second|Byosoku 5 centimeter ~a chain of short stories about their distance~|5 Zentimeter pro Sekunde|5 Centimetri al Secondo|Пять сантиметров в секунду|5 cm na sekundę|5 centymetrów na sekundę|5 centimeter i sekunden|5 سنتيمترات في الثانية|5 εκατοστά το δευτερόλεπτο|5 ס"מ בשנייה|5 centimetrai per sekundę|Saniyede 5 Santimetre|5 centimetri pe secundă|5 centimét một giây|5 Cm Một Giây|Пет сантиметра на секунда|5 сантиметра в секунда|Byosoku Go Senchimetoru|Byousoku Go Senchimeetoru|Byousoku Go Senchime-toru|5 сантиметрів на секунду|5 сантиметрів за секунду|5cm/s|5cm per Second|5cm|秒速5センチメートル|5 Centimeters per Second|5 Centimeters per second|5 Centimètres par seconde|5 Centímetros por Segundo|5 сантиметров в секунду|초속 5 센티미터|5 Centimetru za Sekundu|5 centimeter per seconde|Másodpercenként 5 centiméter|5 sentimeetrit sekundis|秒速5厘米|Секундэд таван сантиметр" ```

So even with full list of titles we cannot make anything from them. I could add some kind of indicator which is which but the question which are important. For now I will try to get those: Main Title (x-jat) and Official Title (EN) and Official Title (JP - because this is JP ART) 

Fallback would be from EN/JP to Main Title. 3 Option to pick EN/JP/Main Title

WIP

**Comment by bigretromike** [comment]
New conception, because there is need to make bigger changes Im using every lang that is inside my titles table :-) (53 current)

**Comment by bigretromike** [comment]
Even better. Who need list of supported langs when you can type in most cases 2 letters and done :) instant support

**Comment by bigretromike** [comment]
Did i said WIP ? Nah its finished.

Official + your lang you pick in settings, if not then Main + your lang, if not then MainTitle which is title

**Comment by bigretromike** [comment]
This also need a newest version of JMM which is this merge: https://github.com/japanesemediamanager/jmmserver/pull/203
