### ISSUE TITLE
Unable To Load Series With Lots Of Episodes

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#30]
When attempting to load a series with a lot of episodes (Gintama, Bleach, Naruto...etc) the plugin returns either an error or an empty episode listing.

**Comment by bigretromike** [comment]
Error is for Timeout, empty list is probably because some throw and catch error.
Got Naruto, will get Gintama to try to reproduce this error.

**Comment by bigretromike** [comment]
meanwhile there is a semi-fix with setting the timeout in settings in version 1.1.5, 
I could split full anime list into every 100 episodes but would that be good aproche? In worst case scenario when not uusing "current watching" you have to wait more than for full list - depending how many episodes you got. I will try to reduce the size of respond to shorter the time, but till then. Please change timeout settings from 60 (default) from version 1.1.5 and up

**Comment by anzerman** [comment]
seeing this issue with one piece too. where can I change this timeout setting? also the other option although maybe taboo could be to organise episodes in to the season structure that is on trakt. at least that breaks down episodes into arcs. although I would still like to see absolute numbers for episodes...

**Comment by ElementalCrisis** [comment]
@bigretromike fixed it in the dev build, here's a workaround for now.

Navigate to %AppData%\Kodi\userdata and create a file called advancedsettings.xml and add the following:

```
<advancedsettings>
<playlisttimeout>60</playlisttimeout>
</advancedsettings>
```

Restart Kodi and you should be good to go. If the problem still persists change the timeout to something higher than 60.

**Comment by bigretromike** [comment]
@anzerman the way files are organizate is same as the AniDB/JMM dose. If you have something other than episodes (like specials, extra) the series get splitted for Folder like: Episodes, Specials. 
True long series could be organizated in other way but we are relaying here on way AniDB do it :-) 

If you are using version 1.1.5 or higher, you can check in plugin settings that there is a TimeOut setting.
Depending on your needs/cpu power/connection configuration - you can make it higher.

You dont benefit from lower value, so you can go the high you like.

@ElementalCrisis thanks for the tip about playlisttimeout :+1: I didnt know about this one
