### ISSUE TITLE
Total Duration Not Calculating Correctly

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#32]
When viewing a series, the Total Duration is displaying the Total Duration for all files in your collection, not the selected series. 

http://elementalcrisis.github.io/images/nakamori/nakamori-series-overview.png

**Comment by bigretromike** [comment]
From super quick look up its miss calculated time for series/episode. Investigating in few hours

**Comment by bigretromike** [comment]
Also when sorting by is change to duration there is alos the problem theres.
Total duration is calculated from those values.
