### ISSUE TITLE
Report broken Anime series here

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamoriplugin#43]
If anyone have problem with any series.
Please describe the problem and put name of anime + group here so I can reproduce the problem if needed

**Comment by ElementalCrisis** [comment]
Anime: Bleach
Groups: Mixed (Lunar, DB, SGKK)
Download Link: https://www.nyaa.eu/?page=view&tid=314574

The movies load fine but it will not show the series episodes.

**Comment by ElementalCrisis** [comment]
Anime: Code Geass - Lelouch of the Rebellion R1
Group: OZC
Download Link: https://www.nyaa.eu/?page=view&tid=736306

Anime: Code Geass - Lelouch of the Rebellion R2
Group: OZC
Download Link: https://www.nyaa.eu/?page=view&tid=736340

Both series will not load any files such as episodes, specials, openings..etc. However it does show an arrow next to the series when I indicated that I had watched an episode.

**Comment by bigretromike** [comment]
@ElementalCrisis I also have Bleach (mixed) Currently JMM didnt link episodes so I also have empty series. Is this same case for you?

**Comment by bigretromike** [comment]
@ElementalCrisis for Code Geass. Did you use Search or All option ? 
I see it without problem via both.
![code](https://cloud.githubusercontent.com/assets/6052025/12224021/fa49bea4-b7e6-11e5-91ed-640563b6f52b.png)

What version of Nakamori are you using ? (still getting my hands on that bleach)

**Comment by ElementalCrisis** [comment]
I'm running Version 1.2.2. Here's the interesting thing, it does not show up when I navigate to Code Geass under the ALL filter but I can pull it up via the SEARCH filter.

**Comment by bigretromike** [comment]
After session it looks like we have nested groups

**Comment by ElementalCrisis** [comment]
Awesome job, all anime series I was having problems with now display correctly!

**Comment by bigretromike** [comment]
case closed!
