### ISSUE TITLE
Request: On deck feature

### ISSUE THREAD

**Issue by KaySeeOne** [bigretromike/nakamoriplugin#52]
Like the continue watching feature but only show unwatched episodes.
On long running series scrolling to the next unwatched episode can be a bit annoying.
My initial thoughts is either like the Plex 'On Deck' or using the existing 'continue watching (system)' but auto scrolling to the next unwatched episode. Actually I wonder if this can be achieved with a new filter, I have had a quick look but I can't see how.

**Comment by bigretromike** [comment]
Sorry because I don't use Plex. 
Currently if you noticed all unwatched episodes are selected - Which is good.
I Could add Item on list on top of it with "continue" option - Would that be usefull ?
You could enter "Continue watching (system) " (I hate that name) and pick series you watched and first item would be "continue watching' and done. No need to scroll and look which you watched 

Is the idea good ?

**Comment by KaySeeOne** [comment]
Hi,

 

Yes, it’s the scrolling through 200 odd episodes that is the issue, and having an ‘On deck’ page would be nice just having not having to scroll would be sufficient.

 

And I agree the name ‘Continue Watching (System)’ is horrible but just dropping the ‘(System) would make it bearable, is it hard codded in JMM or can it be changed?

 

Keith.

**Comment by bigretromike** [comment]
It is hardcoded in JMM which is sheard between kodi and plex, but I will probably just rename it in Nakamori so I wont break Plex (if plex realy need that horible name) 

I will try to add that "special" item. Mean while I will try to get info about that "on Desk" plex function.

**Comment by KaySeeOne** [comment]
Hi,

 

Great.

 

The Plex ‘On deck’ feature is quite simple in concept but probably difficult to program, I would assume, because I have never seen it in any other media centre type program.

In simplest terms it is a single page showing the next episode of each series that you have started to watch, e.g. If you have watch episodes 1 to 7 of ‘Fairy Tail’ and 1 to 114 of ‘Bleach’ but haven’t watched any episode of ‘Angel Beats!’ but you have watched every episode of ‘Claymore’ and you only have those four shows in your library the page would only show two episodes: ‘Fairy Tail episode 8’ and ‘Bleach episode 115’.

 

Keith.

**Comment by bigretromike** [comment]
It is hardcoded in JMM which is sheard between kodi and plex, but I will probably just rename it in Nakamori so I wont break Plex (if plex realy need that horible name) 

I will try to add that "special" item. Mean while I will try to get info about that "on Desk" plex function.

**Comment by bigretromike** [comment]
Fighting with playlist - nightmare... I do have playlist, which work, but kodi show it as empty... semi win but I want to make it work the real way...

**Comment by bigretromike** [comment]
I droped 'playlist' for now, but added '-continue-' item on beginning of every episode folder
