### ISSUE TITLE
Bug: Episodes not being listed

### ISSUE THREAD

**Issue by KaySeeOne** [bigretromike/nakamoriplugin#53]
When selecting certain shows there are no episodes listed.
So far two of my shows exhibits this behaver, Freezing (a7900) and Deadman Wonderland (a7902).
Both list and play correctly in the Plex plugin.
I at first thought it might be that they have subsection's, e.g. Episodes, credits & specials, with content; but 009-1 (a4367) has a special and works fine.
I added a (bogus) credit to 009-1 and it still worked.
Freezing episodes are mp4 h264, Deadman is mkv h264 and so is 009-1; I can't see anything odd with the file formats of those that don't work in Nakamori.
They are all in subdirectories of the same parent directory.

**Comment by bigretromike** [comment]
all right then.
Do you use Nakamori version 1.2.3 ? If you install it from REPO I will now update it to corespond that version. If you ARE using this version please write about it :-)

**Comment by KaySeeOne** [comment]
Hi,

 

I installed the plugin yesterday from the repo on my shiny new Nvidia Shield, but it’s still version 1.2.2 but the update button is greyed out. Also my old HTPC is on the same version with greyed out update button, also exhibits the same behaviour.

 

Keith

**Comment by bigretromike** [comment]
I just updated repo. To force update, just close Kodi and open it again. 
Or you can go into System > Settings> Add-ons > My addons > Video addons > Nakamori

**Comment by bigretromike** [comment]
The nested groups you are probably using been fixed in 1.2.3 in this issue: https://github.com/bigretromike/nakamoriplugin/issues/43

**Comment by KaySeeOne** [comment]
Hi.

 

The update isn’t working for me, I’ve shutdown Kodi, rebooted the machine, uninstalled and reinstalled the Nakamori  plugin to no avail.

 

Keith.

**Comment by KaySeeOne** [comment]
Ok I decided to uninstall and install from zip
And it did fix the problem thanks,

**Comment by bigretromike** [comment]
This is strange, I will check if everything is ok with repo then. But I can close this issue now.
