### ISSUE TITLE
NVidia Shield (Android)

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamoriplugin#54]
Crash every time on episode stop. - he dont like our custom player?
couldnt' update from repo

**Comment by KaySeeOne** [comment]
Hi,
Here's the log from the Nvidia Shield,
[kodi.txt](https://github.com/bigretromike/nakamoriplugin/files/92732/kodi.txt)

I can't see anything obvious, but then I don't know what to look for :confounded:

**Comment by bigretromike** [comment]
I dont see any problems in log, sadly - but that wont stop me from trying to fix this :-)

Only what I see is sync error in middle of playing video...

And something android related :-)

**Comment by KaySeeOne** [comment]
One thing I found, if you escape back to the menu during the end credits, leaving the video playing, Kodi doesn't crash. But something strange happens with the watched status, it seems to set the watched status twice, first time it sets it a tick appears next to the episode listing, next time it sets it the tick disappears. And when I check in JMM it is unwatched.
Here's a log file with debug switched on 
[kodi.txt](https://github.com/bigretromike/nakamoriplugin/files/93370/kodi.txt)

I renamed it to .txt as strangely GitHub doesn't allow .log files to be uploaded, very weird as it is an issue tracking system.

**Comment by bigretromike** [comment]
Ok, probably thats the case. It should do it twice. at percent and at end.

**Comment by bigretromike** [comment]
- [ ] crash on to long load
- [ ] crash after playing video

Confirm on generic android.
Investigating

**Comment by bigretromike** [comment]
I tested newest dev build: 1.2.7 on my phone (Android) and it workflawless now :-) :+1:  please try and if there is still problem give me a message
