### ISSUE TITLE
Use MainTitle Instead Of Official Not Working

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#55]
I noticed that this feature does not seem to be working. The official name for this series, https://anidb.net/perl-bin/animedb.pl?show=anime&aid=8971 is La Storia della Arcana Famiglia yet regardless if this option is enabled or not the series is still listed as Arcana Famiglia: La Storia della Arcana Famiglia.

**Comment by bigretromike** [comment]
It looks like the part of that code got deleted some way :-) 

Which means its not a bug, because its not there :+1:

**Comment by bigretromike** [comment]
https://github.com/bigretromike/nakamoriplugin/commit/2d6033e0ec886197332ddff88407e4f68667faf6 this one deleted it

**Comment by bigretromike** [comment]
And somehow patch for jmm aint there. What happend ?! I dont have idea!

**Comment by bigretromike** [comment]
My fault, didnt made it for ALL ;-)

**Comment by bigretromike** [comment]
1.2.4 + JMMServer update (3.4.6.4 i suppose? )
