### ISSUE TITLE
Unable To Change Language

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#56]
The language setting does not seem to take effect regardless of what language I try to use. Using the following series for testing, https://anidb.net/perl-bin/animedb.pl?show=anime&aid=6107 I was unable to get it to display any of the other names listed. Even with "en" inputted it still showed the series as "Hagane no Renkinjutsushi".

**Comment by AreFinstad** [comment]
just for a ref, got the same issue with the same show :(

**Comment by bigretromike** [comment]
This was covered by #55 and been fixed
