### ISSUE TITLE
Suggestion: Prompt For Series Voting

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#57]
We can currently vote after watching each episode but a feature to prompt for series voting upon series completion would compliment this feature.

**Comment by bigretromike** [comment]
Its the other way, we VOTE on series but cant on episode. 
This is JMM Server @jmediamanager already investigate and API support it soooo :-)

**Comment by bigretromike** [comment]
Oh. btw. I added support for it on JMMServer :-)

**Comment by AreFinstad** [comment]
trakt can vote on episodes BTW :D 
would be nice if we could atleast vote there.

**Comment by bigretromike** [comment]
we can on anidb right now :-) I remamber about trakt support but that would be great on jmm side, so you vote in every supported client and the server would handle rest. but till then I will add support here and there.
But to trakt work, I need trakt_id... btw. this is not trakt issues ;)

1.2.4 + new JMM Server support episode voting

**Comment by AreFinstad** [comment]
true its a voting issue. 
i do think JMM as a hole needs a larger push towards using trakt tho so they can see the light. never had an issue with finding things on trakt as its a mirror from tvdb, just say that noone is actually linking it for community review :(

**Comment by bigretromike** [comment]
aww.. but if you like it and if jmm support trakt (from what i see it dose) i dont see problem :-)

Will add with next 1-2 version :-) You will have you 'light in tunnel'
