### ISSUE TITLE
Error When Loading Unsort Filter

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#58]
Noticed that Nakamori seems to be unable to load the "Unsort" filter.

[Kodi Error.txt](https://github.com/bigretromike/nakamoriplugin/files/93407/Kodi.Error.txt)

**Comment by bigretromike** [comment]
Mine dont throw error. It is empty. Your throw error right ?

**Comment by ElementalCrisis** [comment]
Yeah my u sorted filter is also empty. When I get home I'll see if I can get it to populate with results by having some files at root level.

**Comment by bigretromike** [comment]
from Support session it looks like jmmserver throw error. 
But thank to this issue i fixed 'Unsort' for everybody else ;-)
