### ISSUE TITLE
Suggestion: Add More Support For Fanart 

### ISSUE THREAD

**Issue by ElementalCrisis** [bigretromike/nakamoriplugin#59]
While switching skins I noticed that different view styles would have blank images for series.

![kodi_2016-01-17_05-45-08](https://cloud.githubusercontent.com/assets/9443295/12377810/19654414-bcdf-11e5-98af-16adff309412.png)

It seems the -fanart.jpg file is usually displayed in this spot and while JMM does not name the downloaded images as such, it does still download the fanart, from the same place (thetvdb.com) Kodi uses. Initially I was going to request to add fanart support but noticed it's already included and being used.

![kodi_2016-01-17_05-54-53](https://cloud.githubusercontent.com/assets/9443295/12377811/19660304-bcdf-11e5-9788-4c0725b1afc5.png)

The image in the background being used is fanart, so what I'd like to request is more support for fanart for different display types since the display types are pretty much consistent across skins. 

Also the theme being used in the images is Mimic, http://kodi.wiki/view/Add-on:Mimic/.

**Comment by bigretromike** [comment]
I like that skin :-) will check it later. I fast looked up and my collection dont have fanarts server by jmm server, probably it use something different. (art).

Need to check why its that way

**Comment by bigretromike** [comment]
- [ ] No image in Add-on selection
- [ ] Gallery / Panel view dont show image

**Comment by ElementalCrisis** [comment]
The settings for downloading fanart are in JMM Desktop, Settings > Community Sites.

**Comment by bigretromike** [comment]
there is some kind of glitch in Main section ;-) working with it

**Comment by bigretromike** [comment]
This have been fixed. in 1.2.5 

also the 'No image in add-on selection' is related with this: https://github.com/bigretromike/nakamoriplugin/issues/8 so it will be fixed in time. Till then thanks for reporting
