### ISSUE TITLE
Popup about not connecting (bad setting)

### ISSUE THREAD

**Issue by bigretromike** [bigretromike/nakamoriplugin#67]
Would be nice for newcommers

**Comment by ElementalCrisis** [comment]
Could this be expanded to include any error messages? I sometimes miss the little box that appears in the top-right corner.

**Comment by bigretromike** [comment]
Top right ?:-) its skin depended where its is but yeah - that is a good idea!

**Comment by bigretromike** [comment]
wrong user, connection problem and buildmenus errors are included
