### ISSUE TITLE
Kodi 16.1 RC2 - Watched flag not syncing consistently

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#71]
As stated, the Watched flag is not consistently synced. After watching, the video is not always marked, and Mark as Watched will toggle the Watched status in Kodi instead of setting it

**Comment by bigretromike** [comment]
Video is not always marked as watched in Kodi Live view or the action "mark as watched' dont trigger ?
Mark as watched does trigger "mark as watched" action because you cannot overwrite it without changing Kodi source.

**Comment by da3dsoul** [comment]
Clicking the mark as Watched button in Kodi will toggle the Watched flag rather than setting it as Watched. See #72 for not always marking it at the end.

**Comment by da3dsoul** [comment]
Aside from the toggling and #72, I think it works. I've still been getting used to JMM and all of its quirks.

**Comment by da3dsoul** [comment]
It doesn't help all three of the parts needed for the setup are basically in beta.

**Comment by bigretromike** [comment]
What do you mean ? About jmm 3.5 version ? Kodi RC version ? or what /

Nakamori use stable version of JMM Server and stable version of Kodi which is 16.0 

I will support both 3.5 JMM and Kodi 16.1 but currently Kodi like to change some major things between RC so yeah ;-) 

If this is what you ment by last post then I will try my best :-)  
I could add restriction that you wont be able to start Nakamori on 'not tested' kodi version but that would be poor ;-)

**Comment by da3dsoul** [comment]
I was saying that I'm running dev versions of both Kodi and JMM, so it's hard to tell if any problem is with Nakamori or something else or a mix of all kinds of things. Kodi Krypton looks like it'll be a pain to update to, and it's not even close to being done.

**Comment by bigretromike** [comment]
Oh, so you are using 3.5 - that is a good info because that could break searching and other things.

**Comment by da3dsoul** [comment]
I'm using the latest commit on GitHub as of 4 days ago. If that is what will be 3.5, then I guess. Kodi I'm just running 16.1 RC2, because ps3 controller support is broken in Krypton right now.

**Comment by da3dsoul** [comment]
The server is just 3.4.6.4, though as the only changes until yesterday were localization

**Comment by bigretromike** [comment]
If I recall correctly they didnt change version in those builds until there will be stable one ;-) so if you using github version its almost 100% sure its 3.5

**Comment by da3dsoul** [comment]
Yeah, so clarification. Server 3.4.6.4. Desktop 3.5. I updated the Desktop because there was a lot of bugfixes. It gets along with the server just fine. The server is getting quite a bit of attention the past few days that might need to be looked at, but one problem at a time I guess.

**Comment by da3dsoul** [comment]
I updated commits on JMM (both) today. If I mark something as Watched, leave the menu and go back, It is not saved.

**Comment by da3dsoul** [comment]
I obviously don't expect things like this to be fixed right away. I just figure it helps to point out things that will require attention for updating.

**Comment by da3dsoul** [comment]
I'm trying again with the option to Mark Files as Watched setting ticked in JMM.

**Comment by da3dsoul** [comment]
Okay, it's not being updated in JMM (or MySQL) at all. The status in Kodi is wiped if it closes or clears its cache of the menu.

**Comment by bigretromike** [comment]
If you checking mark as watched on JMM Client ?
It would lie in Kodi about watched status when you toggle it by keyboard

**Comment by da3dsoul** [comment]
I'm referring to the mark as Watched button in Kodi. As well as the Watched status changing after finishing an episode

**Comment by da3dsoul** [comment]
It works purely in Kodi, but with the sync to JMM setting checked, it doesn't work. Took awhile to narrow that down. I may be able to fix it and pull request it. I'll look into it, but Python has never been my favorite language

**Comment by bigretromike** [comment]
This is my first python project also its not my favorite language

**Comment by da3dsoul** [comment]
Looking at it, I see the toggling is done that way on purpose, I'll see if there is a workaround to either change the string or separate the function into mark as Watched and Mark as unwatched

**Comment by da3dsoul** [comment]
That's funny, I was searching around and saw a link and thought, "that's it!"... http://forum.kodi.tv/showthread.php?tid=258780 but then no...

**Comment by da3dsoul** [comment]
I think I found it! http://forum.kodi.tv/showthread.php?tid=140906&page=2 well, shower then work. I'll see if I can make it work later

**Comment by da3dsoul** [comment]
-Facepalm- Okay, I had my user set to 0 instead of 1. I'm going to check all of the other issues I made.

**Comment by da3dsoul** [comment]
Well, this will be converted into a new issue. Give a message if the selected user is invalid
