### ISSUE TITLE
Kodi 16.1 RC2 - List Auto-Progression fails at the end of a scrollable list

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#72]
It will mark a different episode as not watched in Kodi and progress to the episode after the incorrect episode. The incorrect episode is usually the 4th or 5th in the list, after the -continue-

**Comment by bigretromike** [comment]
So you pick for example 3 episode, watch 3, then list came back episode 4 is marked and it moves to 5?

**Comment by da3dsoul** [comment]
No, it needs to be long enough for scrolling. So for example, scroll down to episode 12, make sure it is at most 3 from the bottom of the viewable page, play it and let it finish (or just skip to the end), then it will exit. It will toggle the mark of an episode that was in the middle of the list (like 6 or 8), and progress to the one after that (6 or 8).

**Comment by bigretromike** [comment]
Could it be that it mark the episode by index of item in list like you watched 1,2,3,4,5 episode, you scroll down, you watch now episode 90, but it marks something that is 5-6 from top (index) on the list you currently see so that would be something like 85-86 ? or its look like something other ?

**Comment by da3dsoul** [comment]
Exactly

**Comment by da3dsoul** [comment]
This one happens with JMM 3.4.6.4. It's probably just a Kodi/Nakamori issue.

**Comment by bigretromike** [comment]
So this is not related to JMM version any way. 
I will try to dig kodi functions doc then but last time I checked it almost half the options didnt work like intended

**Comment by da3dsoul** [comment]
Yeah, programmers are by default math oriented people, which means they are not English/language people...which means unless they have help, documentation falls behind quickly. I run into far too often...and I do it, too, so I can't complain too much.

**Comment by bigretromike** [comment]
yeah ^_^ know that myself

**Comment by da3dsoul** [comment]
I haven't tested extensively yet, but it hasn't happened in the past five minutes since fixing my issue with watched flags...

**Comment by da3dsoul** [comment]
I'll call this related to the user issue at this point, it hasn't caused any problems I've noticed since

**Comment by bigretromike** [comment]
good news thanks for closing

**Comment by da3dsoul** [comment]
It's happened again for me, but only once. If I notice it again, I'll try and find some useful info
