### ISSUE TITLE
Unwatched episodes subtext on TV shows uses AniDB total

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#77]
It uses the total number of episodes that AniDB provides instead of the total number you have, including specials. It causes things to say they are unfinished even though you have watched all of the episodes but not the specials, no credit opening, etc

This occurs in JMM 3.4.6.4 and Kodi 16.0.

**Comment by da3dsoul** [comment]
For example, soul eater has like 26 specials...

**Comment by bigretromike** [comment]
Nakamori do use AniDB info for anything, it use JMM info. And JMM use AniDB info so it can bit tricky to fix this, because specials for series are inside series 'folder' and if Nakamori check this as watched without specials you could probably miss those specials even not knowing about them.

Im not sure if this would be intended - The only solution would be to introduce this to JMM to make option to make them seperate as groups

**Comment by da3dsoul** [comment]
I'm going to make a log spam for myself, I'll post any useful info I find out regarding anything.

**Comment by bigretromike** [comment]
sure and I will either way try to see what can I do from Nakamori ends ;-)

**Comment by da3dsoul** [comment]
Meh, I'm officially going to make a pr to jmm to add the things we'll need for convenience. Number of Specials is one thing, number of missing episodes wouldn't be a bad idea (especially since the current state will say a series is unfinished if you are missing episodes). Can you think of anything else?

**Comment by da3dsoul** [comment]
Kodi 16.1 stable literally just came out

**Comment by bigretromike** [comment]
yeah, downloading it and testing :-)

**Comment by bigretromike** [comment]
JMM is the one that tell how many episode is in series. And it doesnt tell how many you have localy. 
I added this because this could be better solution and workaround for those specials/drama you mention before.
We will see if anyone else will need this as much :+1:

**Comment by da3dsoul** [comment]
Yeah, I've started on the JMM work, but it's really big, and I'm still familiarizing myself with the code

**Comment by bigretromike** [comment]
Yes it is really big and sometimes there are more hacks than solution :+1: also maybe one they some developers will move it to mono c# to make it crosscompatible
