### ISSUE TITLE
Give a message if the user is invalid

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#78]
cause yeah, it caused me to make a bunch of issues I need to recheck

**Comment by bigretromike** [comment]
you refer for user as jmm user?

**Comment by da3dsoul** [comment]
Yes

**Comment by da3dsoul** [comment]
If it's set as something other than 1, it causes lots of things to not work right...

**Comment by bigretromike** [comment]
its strange that it worked anyway

**Comment by da3dsoul** [comment]
I know right, I it only cares about the user for Watched States. I'm really surprised voting still worked

**Comment by bigretromike** [comment]
that jmm fault then :-) maybe it work like if there isn't any user with this ID then fallback to default one :+1: that would make sense ans few of those fallback aint there so some functions are broken

**Comment by da3dsoul** [comment]
That would be good, but annoying if it's half way done.

**Comment by bigretromike** [comment]
This have been added to my local build. I will try to push it as quick as I manage to resolve few more issues
