### ISSUE TITLE
Put the top five tags in the Genre info section

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#79]
it'd be nice

**Comment by bigretromike** [comment]
top 5 as the most used ? or last searched ?

**Comment by da3dsoul** [comment]
No, in the information section where it says the plot, it has a spot for Genre, but everything just says unavailable. So, it would display the first 5 tags in the list for whatever show it is.

**Comment by bigretromike** [comment]
Those information are empty because of JMM, will fix that

**Comment by da3dsoul** [comment]
Yeah, when I dumped the info for a bunch of files, it looked like the tag value was named differently.

**Comment by bigretromike** [comment]
more like missing :-) same with years etc
also the AniDB Rating Filter you mention before is broken inside JMMServer and throw error :+1: 

Im working on those missing things but currently JMM broke something inside database so I will probably will start fresh one because 'Contiune watching (system)' dissapear

**Comment by da3dsoul** [comment]
Yeah, that's just broken on your end. I've got all that being sent to Nakamori, just not parsed correctly. Well, except for the anidb rating error, that's just broken

**Comment by da3dsoul** [comment]
06:15:52 T:9136  NOTICE: addGuiItem - details
06:15:52 T:9136  NOTICE: - aired -
06:15:52 T:9136  NOTICE: - rating - 'unset'
06:15:52 T:9136  NOTICE: - tvshowname - The Future Diary
06:15:52 T:9136  NOTICE: - castandrole -  | ('Muru Muru', '') | ('Amano Yukiteru', '') | ('Gasai Yuno', '') | ('Uryuu Minene', '') | ('Kousaka Ouji', '') | ('Deus ex Machina', '') | ('John Bacchus', '') | ('Hirasaka Yomotsu', '') | ('Hino Hinata', '') | ('Kasugano Tsubaki', '') | ('Kurusu Keigo', '') | ('Akise Aru', '') | ('Mikami Ai', '') | ('Houjou Reisuke', '') | ('Nonosaka Mao', '') | ('Miyashiro Orin', '') | ('Onna Kyoushi', '')
06:15:52 T:9136  NOTICE: - episode - 27
06:15:52 T:9136  NOTICE: - title - The Future Diary
06:15:52 T:9136  NOTICE: - season - 0
06:15:52 T:9136  NOTICE: - sorttitle - The Future Diary
06:15:52 T:9136  NOTICE: - originaltitle - {main:x-jat}Mirai Nikki Redial: Data Ikou|{official:ja}未来日記リダイヤル データ移行
06:15:52 T:9136  NOTICE: - plot - * Based on a manga by http://anidb.net/cr23009 [Esuno Sakae], serialised in http://anidb.net/cr11434 [Shounen Ace].
                                            The Second is dead and the http://anidb.net/ch25306 [Gasai Yuno] in the third world finally gets to live a happy life with her loving parents and friends from school. But there is still an empty place in her heart — it seems she has forgotten a person really close to her but simply cannot regain her memories...
                                            Source: ANN
                                            Note: Bundled with the Future Diary Redial (Mirai Nikki Redial) manga volume on 26.07.2013. Also received a special broadcast on NicoNico Douga on 19.06.2013.
06:15:52 T:9136  NOTICE: - mpaa -
06:15:52 T:9136  NOTICE: - cast -  | Muru Muru | Amano Yukiteru | Gasai Yuno | Uryuu Minene | Kousaka Ouji | Deus ex Machina | John Bacchus | Hirasaka Yomotsu | Hino Hinata | Kasugano Tsubaki | Kurusu Keigo | Akise Aru | Mikami Ai | Houjou Reisuke | Nonosaka Mao | Miyashiro Orin | Onna Kyoushi
06:15:52 T:9136  NOTICE: - dateadded - 'unset'
06:15:52 T:9136  NOTICE: - year - 0
06:15:52 T:9136  NOTICE: - genre -
06:15:52 T:9136  NOTICE: - votes - 'unset'
06:15:52 T:9136  NOTICE: addGuiItem - extraData
06:15:52 T:9136  NOTICE: - fanart_image - http://127.0.0.1:8111/JMMServerREST/GetImage/7/1299
06:15:52 T:9136  NOTICE: - source - tvshows
06:15:52 T:9136  NOTICE: - thumb - http://127.0.0.1:8111/JMMServerREST/GetThumb/1/8395/0.6667
06:15:52 T:9136  NOTICE: - key - http://127.0.0.1:8111/JMMServerKodi/GetMetadata/1/2/812
06:15:52 T:9136  NOTICE: - partialTV - 1
06:15:52 T:9136  NOTICE: - TotalEpisodes - 27
06:15:52 T:9136  NOTICE: - WatchedEpisodes - 2
06:15:52 T:9136  NOTICE: - type - video
06:15:52 T:9136  NOTICE: - ratingKey - 0
06:15:52 T:9136  NOTICE: - UnWatchedEpisodes - 25

06:21:18 T:7056  NOTICE: addGuiItem - details
06:21:18 T:7056  NOTICE: - rating - 6.76
06:21:18 T:7056  NOTICE: - aired - 2016-01-23
06:21:18 T:7056  NOTICE: - season - 1
06:21:18 T:7056  NOTICE: - tvshowtitle -
06:21:18 T:7056  NOTICE: - sorttitle - Why Is This Happening to Me? I Didn`t Do Anything Wrong!
06:21:18 T:7056  NOTICE: - director -
06:21:18 T:7056  NOTICE: - genre -
06:21:18 T:7056  NOTICE: - year - 2016
06:21:18 T:7056  NOTICE: - duration - 0:24:26
06:21:18 T:7056  NOTICE: - size - 594428809
06:21:18 T:7056  NOTICE: - plot - Tosaki takes over the Ajin search for the government. Thugs attack Kei and Kaito for the Ajin reward money.
06:21:18 T:7056  NOTICE: - votes - 4
06:21:18 T:7056  NOTICE: - episode - 2
06:21:18 T:7056  NOTICE: - title - Why Is This Happening to Me? I Didn`t Do Anything Wrong!
06:21:18 T:7056  NOTICE: - tagline -
06:21:18 T:7056  NOTICE: - writer -
06:21:18 T:7056  NOTICE: - originaltitle - Nande Konna Koto ni Nattanda. Boku wa Warukunai no ni
06:21:18 T:7056  NOTICE: - cast -
06:21:18 T:7056  NOTICE: - mpaa -
06:21:18 T:7056  NOTICE: - playcount - 1
06:21:18 T:7056  NOTICE: addGuiItem - extraData
06:21:18 T:7056  NOTICE: - fanart_image - http://127.0.0.1:8111/JMMServerREST/GetImage/7/2122
06:21:18 T:7056  NOTICE: - VideoCodec - v_mpegh/iso/hevc
06:21:18 T:7056  NOTICE: - resume - 0
06:21:18 T:7056  NOTICE: - height - 720
06:21:18 T:7056  NOTICE: - AudioLanguage - japanese
06:21:18 T:7056  NOTICE: - key - http://127.0.0.1:8111/JMMServerKodi/GetMetadata/0/7/310
06:21:18 T:7056  NOTICE: - xAudioCodec - v_mpegh/iso/hevc
06:21:18 T:7056  NOTICE: - duration - 1466
06:21:18 T:7056  NOTICE: - AudioCodec - aac
06:21:18 T:7056  NOTICE: - thumb - http://127.0.0.1:8111/JMMServerREST/GetImage/6/7673
06:21:18 T:7056  NOTICE: - xVideoAspect - 1.78
06:21:18 T:7056  NOTICE: - xAudioChannels - 2
06:21:18 T:7056  NOTICE: - type - Video
06:21:18 T:7056  NOTICE: - source - tvepisodes
06:21:18 T:7056  NOTICE: - AudioChannels - 2
06:21:18 T:7056  NOTICE: - jmmepisodeid - 448
06:21:18 T:7056  NOTICE: - xVideoCodec - aac
06:21:18 T:7056  NOTICE: - xVideoResolution - 720
06:21:18 T:7056  NOTICE: - parentKey - http://127.0.0.1:8111/JMMServerKodi/GetMetadata/1/3/19
06:21:18 T:7056  NOTICE: - width - 1280

I guess it isn't there

**Comment by bigretromike** [comment]
mind shearing code you added for this output ? this looks useful :-)

**Comment by bigretromike** [comment]
Fix'd but why show first 5 ?:) lets first show all of them, because the orded is random

**Comment by da3dsoul** [comment]
I said that because some things have an usually large number of useless (and entertaining) tags.

**Comment by da3dsoul** [comment]
Put this at the beginning of addGuiItem

```
    if details is not None:
        xbmc.log("addGuiItem - details")
        for i in details:
            tempLog=""
            a=details.get(a)
            if a is None:
                tempLog="-unset-"
            elif isinstance(a,list):
                for b in a:
                    tempLog=tempLog+" | "+b
            xbmc.log("-"+i+"- "+str(tempLog))
    
    if extraData is not None:
        xbmc.log("addGuiItem - extraData")
        for i in extraData:
            tempLog=""
            a=extraData.get(i)
            if a is None:
                tempLog="-unset-"
            elif isinstance(a,list):
                for b in a:
                    tempLog=tempLog+" | "+b
            xbmc.log("-"+i+"- "+str(tempLog))
```

**Comment by da3dsoul** [comment]
I rewrote that from scratch at work. It has a couple issues. I'll a pr for a couple useful things after I'm done testing, one of which is my log spam system (it has a setting too!)

**Comment by da3dsoul** [comment]
http://pastebin.com/KmDSAJjE This may help a bit...

**Comment by da3dsoul** [comment]
http://pastebin.com/N92FxSpj

**Comment by bigretromike** [comment]
This is now close because you and I fixed this :+1:
