### ISSUE TITLE
Remove AniDB links and brackets from plot descriptions

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#82]
As it is now, it will say, "HTTP://...AniDB...[Some Person or Title]  did something"

Preferably, it would say, "Some Person or Title did something"

**Comment by da3dsoul** [comment]
I've already started on this. It's got some weirdness, but it'll be so much less distracting

**Comment by bigretromike** [comment]
great. this should be easy regex function. I think I will try to work this also so we can pick better solution (or I will learn something anyway)

**Comment by da3dsoul** [comment]
Mine's just a list iteration and replacement. Regex takes too much effort (whether for me, the CPU, or both, idk)

**Comment by bigretromike** [comment]
Added to newest version (current local one)

**Comment by da3dsoul** [comment]
Yeah, mine's done, too.

**Comment by bigretromike** [comment]
lets see what you did there ;-)

**Comment by da3dsoul** [comment]
I'm at work now, I'll post in 3.5 hours when I get off. I've always thought it's entertaining how I'm on GMT -5 and be on the same schedule as people on the other side of the planet

**Comment by da3dsoul** [comment]
Okay, after examining logs, we'll go the regex route, There are some plot summaries that are formatted funny.
