### ISSUE TITLE
Remove useless tags before displaying them

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#85]
Anything with "delete" in it
Meta tags
Target audience
Elements
Content indicators
Themes

Post any others you can think of

**Comment by bigretromike** [comment]
I think this will be a bit of tilting at windmills because those are taken from 3 (or more?) service I would probably focus more on searching via TAG than cleaning what you see. Also cluttering main file with blacklist of tags isin't best thing - wouldn't it be better to clean them when parsing from service inside JMM so all othere plugins using JMM as base was also clean?

**Comment by da3dsoul** [comment]
Setting
Place
Present
Earth

So we are clear, by useless, I mean anything that is for AniDB use (like meta tags), anything obvious it redundant (like setting, place, or earth), or something completely subjective (like present, as in 5 years, it becomes not the present)

**Comment by da3dsoul** [comment]
Yes and no. My issue is not so much that they exist, but that they clutter the info section. If something like this were to be proposed to JMM, it would need to agreed upon, as all other functions would be unable to use them. If it were merely cosmetic, we could enable or disable it with a checkbox

**Comment by bigretromike** [comment]
hehehe I see you like to take advantage of options :-) they getting bigger and bigger ;-)
But I like this also but this making more and more scenarios that need to be tested. Like Android etc... :+1: But im happy I catch up to repo with my local copy so your new merges will be less problematic for me to copy onto my version ;-)

**Comment by da3dsoul** [comment]
Yeah, that's why I've made sure not add any imports that may not be available. I'm pretty sure re is included in Python, so regex should be fine where it's needed. I can also test on Android if you need me to.

**Comment by da3dsoul** [comment]
I can throw together a Linux vbox, too, if needed, but the point of using Python for addons is the fact it is cross platform

**Comment by bigretromike** [comment]
If you have time that would be helpful. Eventually I will test it myself to have the idea if it works or not, because there is alot of Android TV Boxs out there

**Comment by bigretromike** [comment]
Yes, but if you would see some archive issues with android you would see that my work worked on PC but throw errors on Android, and I ended up with rewriting 80% of code to be sure it works with Jarvice (16.0) and Android.

**Comment by bigretromike** [comment]
TO BE MOVED TO EPISODE
TO BE MOVED TO CHARACTER

**Comment by bigretromike** [comment]
cast
character related tags which need deleting or merging
meta tags
new

**Comment by da3dsoul** [comment]
Mk, everything that works on desktop as of now works on Android Marshmallow (6.0)

**Comment by bigretromike** [comment]
@da3dsoul thank you for your time

**Comment by da3dsoul** [comment]
An interesting thing I found that isn't such a big deal. If you try to access a show from a user while it is being played (by the same user) on a different machine, it gives a Connection Refused message from JMM.

**Comment by bigretromike** [comment]
weird but I never  tested jmm with more than 1 machine at a time xD

**Comment by da3dsoul** [comment]
I've started work on this, I'm putting it in its own file to save space and readability

**Comment by bigretromike** [comment]
That would be the best thing, because we could update that 'dictionary' easier

**Comment by da3dsoul** [comment]
Indeed, you know in case, rather than finishing the list they have, AniDB decides to make yet another TO BE list.
