### ISSUE TITLE
[Kodi 17] Default skin can't read images properly

### ISSUE THREAD

**Issue by da3dsoul** [bigretromike/nakamoriplugin#91]
Fanart seems to be okay. Banners are cropped versions of the fanart. Posters are nonexistent.

**Comment by da3dsoul** [comment]
This is for the future, as Kodi 17 is still purely nightlies. I've just been keeping an eye on it, as it has a very nice ui and better gamepad support. More importantly, a more streamlined and reliable video player, which hasn't been updated since 2009

**Comment by da3dsoul** [comment]
Okay, that's odd.... The shift view type has posters working, but it's the only one

**Comment by da3dsoul** [comment]
Have some pretty screenies of ui and interesting bugs
These are all with the fanart viewtype, because it looks the least stupid without posters.
![img](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot004.png)
![img](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot005.png)
![img](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot006.png)
![img](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/screenshot007.png)

**Comment by bigretromike** [comment]
there is a old bug in jmm that push non existing images to kodi resulting with alot of missing images even when there are localy fetched but the empty one are used instead. 

https://github.com/japanesemediamanager/jmmclient/issues/242

Maybe that is why some images are missing ?

Btw, is this a default skin for 17 ? if so im in love ;p

**Comment by da3dsoul** [comment]
Ikr, I'm extremely picky about skins, and the only complaint I have is the fanart view lacking tags/Genre, but I'll inevitably make a custom spin off or wait for kover2 to be done/working. Oh, I suppose I did need to edit the default a little to make fanart the default view type

**Comment by da3dsoul** [comment]
Also, it works (most of the time) in Kodi 16.1, so I think it's a Kodi change or issue as of now

**Comment by bigretromike** [comment]
definitly gona look out for this - 17 looks so great. so many things to do :-)

**Comment by ElementalCrisis** [comment]
That's is an awesome looking skin, looks like I might be replacing Mimic.

**Comment by da3dsoul** [comment]
It'll be the default. It's called Estuary.

**Comment by bigretromike** [comment]
https://github.com/japanesemediamanager/jmmserver/commit/d2bd1fbf43da526fd1e4e892800e767e76269346  this should fix missing image problem which is related to this problem

**Comment by bigretromike** [comment]
This have been fixed somewhere around this: https://github.com/bigretromike/nakamoriplugin/commit/47ddbd754daaa4a23d694aec0dc7a65a70b5f945
